// SPDX-License-Identifier: BSD-3-Clause
// Generated by tools/prepare_ripoff_sound.py; see docs/ripoff.md.
function automatic [23:0] background_low(input [2:0] level);
    case (level)
        3'd0: background_low = 24'd744;
        3'd1: background_low = 24'd1403;
        3'd2: background_low = 24'd972;
        3'd3: background_low = 24'd2520;
        3'd4: background_low = 24'd867;
        3'd5: background_low = 24'd1918;
        3'd6: background_low = 24'd1194;
        3'd7: background_low = 24'd4872;
        default: background_low = 24'd744;
    endcase
endfunction
function automatic [23:0] background_high(input [2:0] level);
    case (level)
        3'd0: background_high = 24'd55818;
        3'd1: background_high = 24'd104095;
        3'd2: background_high = 24'd72669;
        3'd3: background_high = 24'd183415;
        3'd4: background_high = 24'd64945;
        3'd5: background_high = 24'd141069;
        3'd6: background_high = 24'd88943;
        3'd7: background_high = 24'd340802;
        default: background_high = 24'd55818;
    endcase
endfunction
function automatic [23:0] laser_clock(input [4:0] level);
    case (level)
        5'd0: laser_clock = 24'd3735426;
        5'd1: laser_clock = 24'd3260797;
        5'd2: laser_clock = 24'd2893185;
        5'd3: laser_clock = 24'd2600062;
        5'd4: laser_clock = 24'd2360870;
        5'd5: laser_clock = 24'd2161980;
        5'd6: laser_clock = 24'd1993996;
        5'd7: laser_clock = 24'd1850235;
        5'd8: laser_clock = 24'd1725810;
        5'd9: laser_clock = 24'd1617064;
        5'd10: laser_clock = 24'd1521211;
        5'd11: laser_clock = 24'd1436085;
        5'd12: laser_clock = 24'd1359982;
        5'd13: laser_clock = 24'd1291539;
        5'd14: laser_clock = 24'd1229654;
        5'd15: laser_clock = 24'd1173429;
        5'd16: laser_clock = 24'd1122121;
        5'd17: laser_clock = 24'd1075112;
        5'd18: laser_clock = 24'd1031883;
        5'd19: laser_clock = 24'd991996;
        5'd20: laser_clock = 24'd955078;
        5'd21: laser_clock = 24'd920809;
        5'd22: laser_clock = 24'd888914;
        5'd23: laser_clock = 24'd859155;
        5'd24: laser_clock = 24'd831324;
        5'd25: laser_clock = 24'd805239;
        5'd26: laser_clock = 24'd780742;
        5'd27: laser_clock = 24'd757691;
        5'd28: laser_clock = 24'd735962;
        5'd29: laser_clock = 24'd715444;
        5'd30: laser_clock = 24'd696040;
        5'd31: laser_clock = 24'd677660;
        default: laser_clock = 24'd3735426;
    endcase
endfunction
function automatic [23:0] torpedo_clock(input [4:0] level);
    case (level)
        5'd0: torpedo_clock = 24'd5895779;
        5'd1: torpedo_clock = 24'd4178782;
        5'd2: torpedo_clock = 24'd3284141;
        5'd3: torpedo_clock = 24'd2737208;
        5'd4: torpedo_clock = 24'd2369751;
        5'd5: torpedo_clock = 24'd2107050;
        5'd6: torpedo_clock = 24'd1910855;
        5'd7: torpedo_clock = 24'd1759553;
        5'd8: torpedo_clock = 24'd1640009;
        5'd9: torpedo_clock = 24'd1543781;
        5'd10: torpedo_clock = 24'd1465193;
        5'd11: torpedo_clock = 24'd1400291;
        5'd12: torpedo_clock = 24'd1346228;
        5'd13: torpedo_clock = 24'd1300906;
        5'd14: torpedo_clock = 24'd1262740;
        5'd15: torpedo_clock = 24'd1230510;
        5'd16: torpedo_clock = 24'd1203257;
        5'd17: torpedo_clock = 24'd1180215;
        5'd18: torpedo_clock = 24'd1160764;
        5'd19: torpedo_clock = 24'd1144389;
        5'd20: torpedo_clock = 24'd1130661;
        5'd21: torpedo_clock = 24'd1119213;
        5'd22: torpedo_clock = 24'd1109725;
        5'd23: torpedo_clock = 24'd1101915;
        5'd24: torpedo_clock = 24'd1095532;
        5'd25: torpedo_clock = 24'd1090343;
        5'd26: torpedo_clock = 24'd1086132;
        5'd27: torpedo_clock = 24'd1082697;
        5'd28: torpedo_clock = 24'd1079843;
        5'd29: torpedo_clock = 24'd1077380;
        5'd30: torpedo_clock = 24'd1075125;
        5'd31: torpedo_clock = 24'd1072898;
        default: torpedo_clock = 24'd5895779;
    endcase
endfunction
