#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Compile an opaque rect/disk MAME colour overlay into row spans and Q8 gains.

This deliberately supports a small static subset, not arbitrary MAME artwork.
Later shapes take priority. A row has one inclusive X span per shape, avoiding
a full colour framebuffer or a per-pixel artwork memory in the FPGA.
"""
import argparse
from fractions import Fraction as F
from math import lcm
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'rtl/video/overlays/starcastle.lay'
BASE = ROOT / 'rtl/video/overlays/starcastle'
WIDTH, HEIGHT, BITS = 512, 384, 9


def compile_layout(path=SOURCE):
    root = ET.parse(path).getroot()
    if root.attrib != {'version': '2'}:
        raise ValueError('Expected MAME layout version 2')
    element = root.find("element[@name='overlay']")
    view = root.find('view')
    screen = view.find('screen/bounds').attrib
    placed = view.find("element[@ref='overlay']")
    if placed.attrib.get('blend') != 'multiply' or placed.find('bounds').attrib != screen:
        raise ValueError('Overlay must multiply and cover the entire screen')
    shapes = []
    for shape in element:
        if shape.tag not in ('rect', 'disk') or len(shape) != 2:
            raise ValueError('Only static opaque rectangles and disks are supported')
        bounds = shape.find('bounds').attrib
        if set(bounds) != {'left', 'top', 'right', 'bottom'}:
            raise ValueError('Explicit edge bounds are required')
        color = shape.find('color').attrib
        if F(color.get('alpha', '1')) != 1:
            raise ValueError('Translucent components are not supported')
        gains = tuple(F(color.get(c, '1')) for c in ('red', 'green', 'blue'))
        if any(not 0 <= g <= 1 or (g * 256).denominator != 1 for g in gains):
            raise ValueError('Colours must be exact Q8 gains in the range 0..1')
        shapes.append((shape.tag, tuple(F(bounds[k]) for k in ('left','top','right','bottom')),
                       tuple(int(g * 256) for g in gains)))
    if not shapes:
        raise ValueError('Empty overlay')
    # MAME fits an element's complete component bounding box to the view item.
    # Star Castle's source Y bounds are .125..875, so its discs become circles
    # on a 4:3 screen, rather than ellipses from using source Y directly.
    left = min(s[1][0] for s in shapes)
    top = min(s[1][1] for s in shapes)
    right = max(s[1][2] for s in shapes)
    bottom = max(s[1][3] for s in shapes)
    rows = [0] * (1 << BITS)
    packed_gains = 0
    for index, (kind, (l,t,r,b), gains) in enumerate(shapes):
        l,r = (l-left)*WIDTH/(right-left), (r-left)*WIDTH/(right-left)
        t,b = (t-top)*HEIGHT/(bottom-top), (b-top)*HEIGHT/(bottom-top)
        if r <= l or b <= t:
            raise ValueError('Degenerate shape')
        denominator = lcm(l.denominator, r.denominator, t.denominator, b.denominator)
        il,it,ir,ib = (int(v * denominator) for v in (l,t,r,b))
        cx,cy,rx,ry = il+ir,it+ib,ir-il,ib-it
        for y in range(HEIGHT):
            py = (2*y+1) * denominator
            if not 2*it <= py < 2*ib:
                continue
            hits = []
            for x in range(WIDTH):
                px = (2*x+1) * denominator
                if not 2*il <= px < 2*ir:
                    continue
                if kind == 'rect' or (px-cx)**2*ry**2+(py-cy)**2*rx**2 <= rx**2*ry**2:
                    hits.append(x)
            if hits:
                span = hits[0] | (hits[-1] << BITS) | (1 << (2*BITS))
                rows[y] |= span << (index * (2*BITS+1))
        packed_gains |= ((gains[0] << 18) | (gains[1] << 9) | gains[2]) << (index*27)
    width = len(shapes) * (2*BITS+1)
    span_text = ''.join(f'{row:0{(width+3)//4}x}\n' for row in rows)
    gain_width = len(shapes)*27
    header = ('// Generated by tools/prepare_overlay.py from CC0 MAME artwork.\n'
              f'localparam integer STARCASTLE_OVERLAY_SPANS = {len(shapes)};\n'
              f'localparam [{gain_width-1}:0] STARCASTLE_OVERLAY_GAINS = '
              f"{gain_width}'h{packed_gains:0{(gain_width+3)//4}x};\n")
    return span_text, header


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    spans, gains = compile_layout()
    for suffix, content in (('_spans.hex',spans),('_gains.svh',gains)):
        path = Path(str(BASE) + suffix)
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f'Stale generated overlay: {path}')
        else:
            path.write_text(content, newline='\n')
    print('PASS: Star Castle overlay spans and gains ' + ('reproduce the layout' if args.check else 'generated'))


if __name__ == '__main__':
    main()
