#!/usr/bin/env python3
"""Generate Rip Off oscillator increments from the pinned circuit reference."""
import argparse
from pathlib import Path
RATE=96000
ROOT=Path(__file__).resolve().parents[1]
def inc(f): return round(f*(1<<24)/RATE)
def table(name,values,width):
 s=f'function automatic [23:0] {name}(input [{width-1}:0] level);\n    case (level)\n'
 for i,v in enumerate(values): s+=f"        {width}'d{i}: {name} = 24'd{inc(v)};\n"
 return s+f"        default: {name} = 24'd{inc(values[0])};\n    endcase\nendfunction\n"
# Background op-amp: -R76 times the three inverted DAC currents.
volts=[-470*5*sum((0 if n&(1<<b) else 1)/r for b,r in enumerate((1000,2000,3300))) for n in range(8)]
out='// SPDX-License-Identifier: BSD-3-Clause\n// Generated by tools/prepare_ripoff_sound.py; see docs/ripoff.md.\n'
out+=table('background_low',[1/(2*(.0179360-.0235033*v)) for v in volts],3)
out+=table('background_high',[1/(2*(.000256399-.000308955*v)) for v in volts],3)
# Use the fitted full-circuit half-period curves over a normalized 0..5 V
# sweep. This is an approximation: analog loading/control evolution is not
# solved here, and the MAME removed-circuit curves are not interchangeable.
levels=[5*n/31 for n in range(32)]
out+=table('laser_clock',[1/(2*(.0000233926+.0000211106*v)) for v in levels],5)
out+=table('torpedo_clock',[1/(2*(.0000148210+.0000390037*v-.0000078207*v*v+.000000536978*v*v*v)) for v in levels],5)
p=ROOT/'rtl/sound/ripoff_clocks.svh'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
if parser.parse_args().check:
 assert p.read_text()==out, 'Regenerate Rip Off oscillator tables'
 print('PASS: Rip Off oscillator tables match circuit-derived formulas')
else: p.write_text(out)
